version: '3.8'
services:
  backend:
    build: ./server
    container_name: medilink-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: medilink-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: medilink-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=MediLink
volumes:
  mongo-data: